### PR TITLE
translation_it

### PR DESCRIPTION
**Pull request by Roby1164**

### CODE REVIEW

**Comment by Tensuko** [comment]
I don't get why your README.md wants to merge... can you update it from our Main first?

**Comment by Roby1164** [comment]
Pull Requests is not working properly.
It keeps asking to create a copy and compare with another branch...... I just need to pass you the translation file

**Comment by Roby1164** [comment]
Screenshot_16

**Comment by KCHARRO** [comment]
I have a similar problem, I updated the xml, but it created Pull Request in the FS22 repository...

In GitHub Desktop it says I don't have permission...

imagen

And when creating a fork it say FS25 is a fork of FS22...

imagen


My file updated to Spanish:
[translation_es.zip](https://github.com/user-attachments/files/18231170/translation_es.zip)

**Comment by Tensuko** [comment]
We will look into this, but somehow some ppl managed to get it working like @KITT3000 and even without have any changes on the README.md

**Comment by KITT3000** [comment]
Yeah, the problem is that the FS25 version is a fork of FS22 and github thinks you want the main repository updated, even after deleting the FS22 fork and creating a new one it tried to merge to the FS22 version, I had to manually change that, but I still additionally updated the repository after forking because it claimed to be 2 changes behind (maybe that's what made that readme.md appear) and to be safe I didn't create a separate branch but to the main one I merged in my repository

**Comment by Roby1164** [comment]
Used alternative route, I think this way works. I close

**Pull request closed without merging**
