### PR TITLE
Add translation_uk.xml

### PR DESCRIPTION
**Pull request by Honcharuk**

### CODE REVIEW

**Comment by Tensuko** [comment]
#89

**Comment by Honcharuk** [comment]
@Tensuko, Since I didn't see these changes in the main repository, I made a pull request. I tried to translate everything clearly, including the help section, but there may be errors because I didn't use all the features of the mod.

**Comment by Tensuko** [comment]
Yea it is just a question for me wich one I should merge now, the one from you or from @Gonimy-Vetrom :)
If you guys discuss this and decide, that would be great :)

**Comment by Honcharuk** [comment]
There may be other translation inaccuracies, but correcting them in the future is better than no localization at all.

**Comment by Honcharuk** [comment]
@Tensuko Since everything in #99 is translated into one language, I think #99. In the future, when @Gonimy-Vetrom has time, he or someone else will be able to correct the text.

**Pull request closed without merging**
